### ISSUE TITLE
Minimal example throws linting errors

### ISSUE THREAD

**Issue by bc3tech** [michidk/winget-updater#11]
I'm using the exact syntax shown in the Minimal Example however the linter in VSCode for the workflow file is throwing the following errors:

* Missing required inputs: `komac-token`, `identifier`
* Invalid action input 'package-id'

My YAML looks like this:

```yaml
  publish-winget:
    needs: 
      - create-release
    runs-on: ubuntu-latest
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@v1
      with:
        package-id: BC3Tech.FileSorter
        repo: bc3tech/filesorter
        url: https://github.com/bc3tech/filesorter/releases/download/{VERSION}/FileSorter_{VERSION}.zip
```
